import { TextHeading } from '@components/textHeading';
import { ScrollView, Text } from '@gluestack-ui/themed';
import React from 'react';
import { Linking } from 'react-native';


export function PrivacyPolicyScreen() {
    return (
        <ScrollView contentContainerStyle={{ padding: 16 }}>
            <TextHeading >Privacy Policy</TextHeading>
            <Text>Last updated: April 16, 2025</Text>

            <Text style={{ marginTop: 10 }}>
                This Privacy Policy describes Our policies and procedures on the collection, use and
                disclosure of Your information when You use the Service and tells You about Your privacy
                rights and how the law protects You.
            </Text>
            <Text>
                We use Your Personal data to provide and improve the Service. By using the Service, You
                agree to the collection and use of information in accordance with this Privacy Policy. This
                Privacy Policy has been created with the help of the{' '}
                <Text style={{ color: 'blue' }} onPress={() => Linking.openURL('https://www.termsfeed.com/privacy-policy-generator/')}>
                    Privacy Policy Generator
                </Text>.
            </Text>

            <TextHeading >Interpretation and Definitions</TextHeading>
            <TextHeading >Interpretation</TextHeading>
            <Text>
                The words of which the initial letter is capitalized have meanings defined under the
                following conditions. The following definitions shall have the same meaning regardless of
                whether they appear in singular or in plural.
            </Text>

            <TextHeading >Definitions</TextHeading>
            <Text>For the purposes of this Privacy Policy:</Text>
            {[
                ['Account', 'means a unique account created for You to access our Service or parts of our Service.'],
                ['Affiliate', 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'],
                ['Application', 'refers to Lancar, the software program provided by the Company.'],
                ['Company', 'refers to Lancar.'],
                ['Country', 'refers to: Indonesia'],
                ['Device', 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.'],
                ['Personal Data', 'is any information that relates to an identified or identifiable individual.'],
                ['Service', 'refers to the Application.'],
                ['Service Provider', 'means any natural or legal person who processes the data on behalf of the Company.'],
                ['Usage Data', 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'],
                ['You', 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.'],
            ].map(([term, def], index) => (
                <Text key={index} style={{ marginVertical: 4 }}>
                    <Text style={{ fontWeight: 'bold' }}>{term}</Text> {def}
                </Text>
            ))}

            <TextHeading >Collecting and Using Your Personal Data</TextHeading>
            <TextHeading >Types of Data Collected</TextHeading>
            <TextHeading >Personal Data</TextHeading>
            <Text>
                While using Our Service, We may ask You to provide Us with certain personally identifiable
                information that can be used to contact or identify You. Personally identifiable information
                may include, but is not limited to:
            </Text>
            {[
                'Email address',
                'First name and last name',
                'Phone number',
                'Address, State, Province, ZIP/Postal code, City',
                'Usage Data',
            ].map((item, index) => (
                <Text key={index}>• {item}</Text>
            ))}

            <TextHeading >Usage Data</TextHeading>
            <Text>
                Usage Data is collected automatically when using the Service. Usage Data may include
                information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser
                type, browser version, the pages of our Service that You visit, the time and date of Your
                visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </Text>

            <Text>
                When You access the Service by or through a mobile device, We may collect certain
                information automatically, including, but not limited to, the type of mobile device You use,
                Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating
                system, the type of mobile Internet browser You use, unique device identifiers and other
                diagnostic data.
            </Text>

            <TextHeading >Use of Your Personal Data</TextHeading>
            <Text>The Company may use Personal Data for the following purposes:</Text>
            {[
                'To provide and maintain our Service, including to monitor the usage of our Service.',
                'To manage Your Account: to manage Your registration as a user of the Service.',
                'For the performance of a contract: the development, compliance and undertaking of a purchase contract.',
                'To contact You: To contact You by email, phone, SMS, or other forms.',
                'To provide You with news, special offers and general information unless You opted out.',
                'To manage Your requests: To attend and manage Your requests to Us.',
                'For business transfers: including merger, acquisition, liquidation, etc.',
                'For other purposes: such as data analysis, identifying trends, and improving the Service.',
            ].map((item, index) => (
                <Text key={index}>• {item}</Text>
            ))}

            <Text>We may share Your personal information in the following situations:</Text>
            {[
                'With Service Providers: to monitor and analyze the use of our Service, to contact You.',
                'For business transfers: in case of a merger, sale of assets, etc.',
                'With Affiliates: we require those affiliates to honor this Privacy Policy.',
                'With business partners: to offer You certain products, services or promotions.',
                'With other users: when You share personal information publicly.',
                'With Your consent: for any other purpose with Your consent.',
            ].map((item, index) => (
                <Text key={index}>• {item}</Text>
            ))}

            <TextHeading >Retention of Your Personal Data</TextHeading>
            <Text>
                The Company will retain Your Personal Data only for as long as is necessary for the purposes
                set out in this Privacy Policy. We will also retain Usage Data for internal analysis purposes.
            </Text>

            <TextHeading >Transfer of Your Personal Data</TextHeading>
            <Text>
                Your information may be transferred to — and maintained on — computers located outside of
                Your jurisdiction. Your consent represents Your agreement to that transfer.
            </Text>

            <TextHeading >Delete Your Personal Data</TextHeading>
            <Text>
                You have the right to delete or request deletion of Your Personal Data. You can do this via
                your Account or by contacting Us.
            </Text>

            <TextHeading >Disclosure of Your Personal Data</TextHeading>
            <TextHeading >Business Transactions</TextHeading>
            <Text>
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
                transferred.
            </Text>

            <TextHeading >Law enforcement</TextHeading>
            <Text>
                The Company may disclose Your Personal Data if required to do so by law or in response to
                valid requests by public authorities.
            </Text>

            <TextHeading >Other legal requirements</TextHeading>
            {[
                'Comply with a legal obligation',
                'Protect and defend the rights or property of the Company',
                'Prevent or investigate possible wrongdoing',
                'Protect the personal safety of Users or the public',
                'Protect against legal liability',
            ].map((item, index) => (
                <Text key={index}>• {item}</Text>
            ))}

            <TextHeading >Security of Your Personal Data</TextHeading>
            <Text>
                While We strive to use commercially acceptable means to protect Your Personal Data, We
                cannot guarantee its absolute security.
            </Text>

            <TextHeading >Detailed Information on Processing</TextHeading>
            <TextHeading >Usage, Performance and Miscellaneous</TextHeading>
            {[
                {
                    name: 'Mouseflow',
                    desc: 'Mouseflow is a session replay and heatmap tool.',
                    url: 'https://mouseflow.com/privacy/',
                },
                {
                    name: 'FreshDesk',
                    desc: 'FreshDesk is a customer support software.',
                    url: 'https://www.freshworks.com/privacy/',
                },
                {
                    name: 'Google Places',
                    desc: 'Google Places is a service that returns information about places.',
                    url: 'https://www.google.com/intl/en/policies/privacy/',
                },
            ].map(({ name, desc, url }, index) => (
                <Text key={index} style={{ marginBottom: 6 }}>
                    <Text style={{ fontWeight: 'bold' }}>{name}</Text>: {desc}{' '}
                    <Text style={{ color: 'blue' }} onPress={() => Linking.openURL(url)}>
                        {url}
                    </Text>
                </Text>
            ))}

            <TextHeading >Children's Privacy</TextHeading>
            <Text>
                We do not knowingly collect personally identifiable information from anyone under the age of
                13. If You are a parent or guardian and You are aware that Your child has provided Us with
                Personal Data, please contact Us.
            </Text>

            <TextHeading >Links to Other Websites</TextHeading>
            <Text>
                Our Service may contain links to other websites that are not operated by Us. Please review
                the Privacy Policy of every site You visit.
            </Text>

            <TextHeading >Changes to this Privacy Policy</TextHeading>
            <Text>
                We may update Our Privacy Policy from time to time. You are advised to review this page
                periodically for any changes.
            </Text>

            <TextHeading >Contact Us</TextHeading>
            <Text>If you have any questions, contact us at: lancarapak@gmail.com</Text>
        </ScrollView>
    );
}
